name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write


jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Build frontend
      run: |
        cd templates/andromodem_fe
        npm install
        npm run build
        cd ../..
      env:
        VITE_ANDROMODEM_VERSION: ${{ steps.version.outputs.version }}

    - name: Build Go binaries for multiple architectures
      run: |
        TAG=${{ steps.version.outputs.version }}
        VERSION=${TAG#v}
        go mod download
        ARCHS=("386" "amd64" "arm" "arm64")
        for arch in "${ARCHS[@]}"; do
          echo "Building for linux/$arch..."
          env GOOS=linux GOARCH=$arch CGO_ENABLED=0 go build \
            -ldflags="-s -w -X main.Version=$VERSION" \
            -o andromodem_${TAG}_linux_$arch \
            ./cmd/andromodem
        done
        ls -la andromodem_*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          andromodem_${{ steps.version.outputs.version }}_linux_386
          andromodem_${{ steps.version.outputs.version }}_linux_amd64
          andromodem_${{ steps.version.outputs.version }}_linux_arm
          andromodem_${{ steps.version.outputs.version }}_linux_arm64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
